# Generated by Django 2.2.6 on 2019-11-04 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('behaviorNLP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='behavior',
            name='be_id',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='con_id',
        ),
    ]
