# Generated by Django 2.2.6 on 2019-11-04 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('behaviorNLP', '0002_auto_20191104_1426'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
